name: CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    
    deploy:
        name: Production Deploy
        needs: security-and-analysis
        runs-on: ubuntu-latest
        environment: Production
        steps:
            - name: Deploy via SSH
              uses: appleboy/ssh-action@master
              with:
                  envs: GITHUB_REPOSITORY
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      # Entra na home do usuário
                      cd ~
                      # Se o projeto não existe, clone. Se existe, pull
                      if [ ! -d "luiz-app" ]; then
                        git clone https://github.com/$GITHUB_REPOSITORY luiz-app
                      fi
                      cd luiz-app
                      git pull origin main
                      docker compose pull
                      docker compose up -d

            - name: Deploy
              run: |
                  echo "Script de deploy para infraestrutura de nuvem"
